### ISSUE TITLE
Release 20240109 known issues

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-server#211]
I'm using this issue to track issues reported by people who have upgraded to the new release. They are candidates for a patch release.

Not all issues here have been confirmed as bugs.

- [x] Users with role 'prosody:normal' explicitly assigned have no permissions after upgrading (#212)
- [x] Newly-registered users do not have circle chats added to bookmarks (#213)
- [x] `Traceback[httpserver]: ...sody/modules/mod_groups_internal/mod_groups_internal.lua:422: attempt to index a nil value` (#213)
- [x] ~~tls-unique may be advertised when unsupported~~ (could not reproduce this, it seems to behave correctly)
